# Generated by Django 4.2.4 on 2023-09-01 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimagecaptions', '0002_rename_extendedrendition_captionedrendition'),
        ('blog', '0003_remove_blogpage_featured_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('read_more_text', models.CharField(default='Read more', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimagecaptions.captionedimage'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='featured_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimagecaptions.captionedimage'),
        ),
        migrations.AlterField(
            model_name='blogpagegalleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimagecaptions.captionedimage'),
        ),
    ]
