# Generated by Django 4.2.4 on 2023-09-01 00:35

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mymodel_alter_blogcategory_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='read_more_text',
            field=modelcluster.fields.ParentalManyToManyField(to='blog.mymodel'),
        ),
    ]
