# Generated by Django 4.2.4 on 2023-09-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpage_read_more_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('read_more_text', models.CharField(default='Read more', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='read_more_text',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
