# Generated by Django 4.2.4 on 2023-09-01 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtagindexpage',
            name='site_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.sitesettings'),
        ),
    ]
