# Generated by Django 4.2.4 on 2023-09-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogtagindexpage_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=255),
        ),
    ]
