# Generated by Django 4.2.4 on 2023-09-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_sitesettings_text_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=255),
        ),
    ]
