# Generated by Django 4.2.4 on 2023-09-01 11:56

import blog.models
from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogpage_show_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='show_body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('video', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('max_width', wagtail.blocks.IntegerBlock(default=1094, max_value=1400, min_value=100)), ('max_height', wagtail.blocks.IntegerBlock(default=529, max_value=1000, min_value=100)), ('title', wagtail.blocks.CharBlock(required=False))])), ('aligned_text', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock()), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')]))])), ('code', wagtail.blocks.StructBlock([('code', wagtail.blocks.TextBlock()), ('language', wagtail.blocks.CharBlock(help_text='Programming language (e.g. python, javascript)', required=False))])), ('raw_html', wagtail.blocks.RawHTMLBlock()), ('blockquote', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock(required=True)), ('name', wagtail.blocks.CharBlock(required=False))])), ('table', wagtail.blocks.StreamBlock([('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', '---------', 'copy', 'cut---------', 'alignment']}))])), ('person', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('fullName_color', wagtail.blocks.TextBlock(help_text='Hexadecimal, rgba, or CSS color notation (e.g. #ff0011)', required=False)), ('pe_image', wagtail.images.blocks.ImageChooserBlock()), ('biography', wagtail.blocks.RichTextBlock()), ('text_color', wagtail.blocks.TextBlock(help_text='Hexadecimal, rgba, or CSS color notation (e.g. #ff0011)', required=False)), ('background_color', wagtail.blocks.TextBlock(help_text='Hexadecimal, rgba, or CSS color notation (e.g. #ff0011)', required=False)), ('description', wagtail.blocks.StreamBlock([('description_item', wagtail.blocks.RichTextBlock(required=False))], required=False))], icon='user')), ('recipe', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('ingredients', wagtail.blocks.ListBlock(blog.models.IngredientBlock)), ('instructions', wagtail.blocks.RichTextBlock())])), ('note', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock())]))], null=True, use_json_field=True),
        ),
    ]
