# Generated by Django 4.2.4 on 2023-09-01 11:58

import blog.models
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailtables.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogpage_show_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='show_body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('video', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('max_width', wagtail.blocks.IntegerBlock(default=1094, max_value=1400, min_value=100)), ('max_height', wagtail.blocks.IntegerBlock(default=529, max_value=1000, min_value=100)), ('title', wagtail.blocks.CharBlock(required=False))])), ('aligned_text', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock()), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')]))])), ('code', wagtail.blocks.StructBlock([('code', wagtail.blocks.TextBlock()), ('language', wagtail.blocks.CharBlock(help_text='Programming language (e.g. python, javascript)', required=False))])), ('raw_html', wagtail.blocks.RawHTMLBlock()), ('blockquote', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock(required=True)), ('name', wagtail.blocks.CharBlock(required=False))])), ('tables', wagtail.blocks.StreamBlock([('table_block', wagtail.blocks.StructBlock([('table_data', wagtail.blocks.TextBlock(default='[]')), ('caption', wagtail.blocks.CharBlock(required=False)), ('header_row', wagtail.blocks.BooleanBlock(required=False)), ('header_col', wagtail.blocks.BooleanBlock(required=False)), ('table_type', wagtail.blocks.ChoiceBlock(choices=wagtailtables.blocks.get_choices))], toolbar=[{'content': 'format_align_left', 'k': 'text-align', 'type': 'i', 'v': 'left'}, {'content': 'format_align_center', 'k': 'text-align', 'type': 'i', 'v': 'center'}, {'content': 'format_align_right', 'k': 'text-align', 'type': 'i', 'v': 'right'}, {'content': 'format_bold', 'k': 'font-weight', 'type': 'i', 'v': '600'}, {'content': 'format_italic', 'k': 'font-style', 'type': 'i', 'v': 'italic'}, {'content': 'border_left', 'k': 'border-left', 'type': 'i', 'v': '1px solid'}, {'content': 'border_right', 'k': 'border-right', 'type': 'i', 'v': '1px solid'}, {'content': 'border_top', 'k': 'border-top', 'type': 'i', 'v': '1px solid'}, {'content': 'format_size', 'k': 'font-size', 'type': 'i', 'v': '16px'}]))])), ('person', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('fullName_color', wagtail.blocks.TextBlock(help_text='Hexadecimal, rgba, or CSS color notation (e.g. #ff0011)', required=False)), ('pe_image', wagtail.images.blocks.ImageChooserBlock()), ('biography', wagtail.blocks.RichTextBlock()), ('text_color', wagtail.blocks.TextBlock(help_text='Hexadecimal, rgba, or CSS color notation (e.g. #ff0011)', required=False)), ('background_color', wagtail.blocks.TextBlock(help_text='Hexadecimal, rgba, or CSS color notation (e.g. #ff0011)', required=False)), ('description', wagtail.blocks.StreamBlock([('description_item', wagtail.blocks.RichTextBlock(required=False))], required=False))], icon='user')), ('recipe', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('ingredients', wagtail.blocks.ListBlock(blog.models.IngredientBlock)), ('instructions', wagtail.blocks.RichTextBlock())])), ('note', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock())]))], null=True, use_json_field=True),
        ),
    ]
