# Generated by Django 4.2.4 on 2023-09-04 20:47

from django.db import migrations, models
import django.db.models.deletion
import home.models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('Topic', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('subtitle', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock())])), ('Images', wagtail.blocks.StructBlock([('image_1', wagtail.images.blocks.ImageChooserBlock()), ('image_2', wagtail.images.blocks.ImageChooserBlock()), ('image_3', wagtail.images.blocks.ImageChooserBlock())])), ('WhatWeDo', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('subheading', wagtail.blocks.CharBlock()), ('description1_title', wagtail.blocks.CharBlock()), ('description1_text', wagtail.blocks.RichTextBlock()), ('description1_link_text', wagtail.blocks.CharBlock()), ('description1_link_url', wagtail.blocks.URLBlock()), ('description2_title', wagtail.blocks.CharBlock()), ('description2_text', wagtail.blocks.RichTextBlock()), ('description2_link_text', wagtail.blocks.CharBlock()), ('description2_link_url', wagtail.blocks.URLBlock())])), ('RightCard', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock()), ('link_text', wagtail.blocks.CharBlock()), ('link_url', wagtail.blocks.URLBlock())])), ('LeftCard', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock()), ('link_text', wagtail.blocks.CharBlock()), ('link_url', wagtail.blocks.URLBlock())])), ('HeadingWithSubheading', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('subheading', wagtail.blocks.CharBlock())])), ('service_list', wagtail.blocks.StructBlock([('services', wagtail.blocks.ListBlock(home.models.ServiceBlock, label='Services'))], label='Service List')), ('service_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('points', wagtail.blocks.ListBlock(wagtail.blocks.RichTextBlock(), required=False))], label='Service Section'))], null=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SurveyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('json', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
