# Generated by Django 4.2.3 on 2023-07-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_remove_socialmediasettings_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='instagram URL', null=True),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='telegram',
            field=models.URLField(blank=True, help_text='telegram Channel URL', null=True),
        ),
    ]
