# Generated by Django 4.2.3 on 2023-07-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_socialmediasettings_threads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='threads',
        ),
    ]
